"""empty message

Revision ID: 59042901afd9
Revises: 
Create Date: 2023-09-13 23:53:03.514747

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '59042901afd9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=20), nullable=False),
    sa.Column('password', sa.String(length=180), nullable=False),
    sa.Column('nombre', sa.String(length=40), nullable=False),
    sa.Column('apellido', sa.String(length=40), nullable=False),
    sa.Column('cedula', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cedula'),
    sa.UniqueConstraint('username')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    # ### end Alembic commands ###
